# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf.xci
# IP: The module: 'data_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf/data_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_buf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf.xci
# IP: The module: 'data_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf/data_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
