set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rx_buf_not_empty]
set_property IOSTANDARD LVCMOS33 [get_ports rx_buf_full]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_send_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports tx_buf_not_full]
set_property IOSTANDARD LVCMOS33 [get_ports en_sig_ld15]
set_property IOSTANDARD LVCMOS33 [get_ports en_sw15]
set_property IOSTANDARD LVCMOS33 [get_ports get_btn_d]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx_pin_jb1]
set_property IOSTANDARD LVCMOS33 [get_ports send_btn_r]
set_property IOSTANDARD LVCMOS33 [get_ports tx_pin_jb0]
set_property PACKAGE_PIN T4 [get_ports tx_pin_jb0]
set_property PACKAGE_PIN N5 [get_ports rx_pin_jb1]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property PACKAGE_PIN R11 [get_ports send_btn_r]
set_property PACKAGE_PIN R17 [get_ports get_btn_d]
set_property PACKAGE_PIN P5 [get_ports {tx_send_data[7]}]
set_property PACKAGE_PIN P4 [get_ports {tx_send_data[6]}]
set_property PACKAGE_PIN P3 [get_ports {tx_send_data[5]}]
set_property PACKAGE_PIN P2 [get_ports {tx_send_data[4]}]
set_property PACKAGE_PIN R2 [get_ports {tx_send_data[3]}]
set_property PACKAGE_PIN M4 [get_ports {tx_send_data[2]}]
set_property PACKAGE_PIN N4 [get_ports {tx_send_data[1]}]
set_property PACKAGE_PIN R1 [get_ports {tx_send_data[0]}]
set_property PACKAGE_PIN T5 [get_ports en_sw15]
set_property PACKAGE_PIN K3 [get_ports en_sig_ld15]
set_property PACKAGE_PIN K1 [get_ports rx_buf_not_empty]
set_property PACKAGE_PIN H6 [get_ports rx_buf_full]
set_property PACKAGE_PIN K6 [get_ports tx_buf_not_full]

set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {an[3]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {an[2]}]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {an[1]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {an[0]}]

set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {seg_code[0]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {seg_code[1]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {seg_code[2]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {seg_code[3]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {seg_code[4]}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {seg_code[5]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {seg_code[6]}]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {seg_code[7]}]



set_property MARK_DEBUG true [get_nets rx_pin_jb1_IBUF]
set_property MARK_DEBUG true [get_nets tx_pin_jb0_OBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list gate_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list tx_pin_jb0_OBUF]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list rx_pin_jb1_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
