# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.cache/wt [current_project]
set_property parent.project_path F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf.dcp
set_property used_in_implementation false [get_files f:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/ip/data_buf/data_buf.dcp]
read_verilog -library xil_defaultlib {
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/reverse_detect.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/out_ctl.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/meta_harden.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/delay_10ms.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/H2L_detect.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/tx_band_gen.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/rx_ctl.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/rx_band_gen.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/tx_ctl.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/L2H_detect.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/btn_debounce.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/code_ctl.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/rx_top.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/tx_top.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/number_encode.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/scan_data.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/uart_top.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/data_show.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/input_signal_processing.v
  F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/sources_1/imports/lab5/uart_demo.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/constrs_1/imports/constr/uart.xdc
set_property used_in_implementation false [get_files F:/fpga_xilinx/fpga/2016.10.25/myself/lab5_uart/lab5_uart.srcs/constrs_1/imports/constr/uart.xdc]


synth_design -top uart_demo -part xc7a35tcsg324-1


write_checkpoint -force -noxdef uart_demo.dcp

catch { report_utilization -file uart_demo_utilization_synth.rpt -pb uart_demo_utilization_synth.pb }
