# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/lab/display_vga/display_vga.cache/wt [current_project]
set_property parent.project_path E:/lab/display_vga/display_vga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
set_property is_locked true [get_files e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top dcm_25m -part xc7a35tcsg324-1 -mode out_of_context
rename_ref -prefix_all dcm_25m_
write_checkpoint -noxdef dcm_25m.dcp
catch { report_utilization -file dcm_25m_utilization_synth.rpt -pb dcm_25m_utilization_synth.pb }
if { [catch {
  file copy -force E:/lab/display_vga/display_vga.runs/dcm_25m_synth_1/dcm_25m.dcp e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir E:/lab/display_vga/display_vga.ip_user_files/ip/dcm_25m]} {
  catch { 
    file copy -force e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_stub.v E:/lab/display_vga/display_vga.ip_user_files/ip/dcm_25m
  }
}

if {[file isdir E:/lab/display_vga/display_vga.ip_user_files/ip/dcm_25m]} {
  catch { 
    file copy -force e:/lab/display_vga/display_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_stub.vhdl E:/lab/display_vga/display_vga.ip_user_files/ip/dcm_25m
  }
}
