# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/fpga_xilinx/fpga/2016.10.24/myself/lab1_flash_led/lab1_flash_led.cache/wt [current_project]
set_property parent.project_path F:/fpga_xilinx/fpga/2016.10.24/myself/lab1_flash_led/lab1_flash_led.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  F:/fpga_xilinx/fpga/2016.10.24/myself/sources/lab1/flash_led_ctl.v
  F:/fpga_xilinx/fpga/2016.10.24/myself/sources/lab1/counter.v
  F:/fpga_xilinx/fpga/2016.10.24/myself/sources/lab1/flash_led_top.v
}
read_xdc F:/fpga_xilinx/fpga/2016.10.24/myself/sources/lab1/constr/flash_led_top.xdc
set_property used_in_implementation false [get_files F:/fpga_xilinx/fpga/2016.10.24/myself/sources/lab1/constr/flash_led_top.xdc]

synth_design -top flash_led_top -part xc7a35tcsg324-1
write_checkpoint -noxdef flash_led_top.dcp
catch { report_utilization -file flash_led_top_utilization_synth.rpt -pb flash_led_top_utilization_synth.pb }
