# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/lab/display_vga/display_vga.cache/wt [current_project]
set_property parent.project_path E:/lab/display_vga/display_vga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files E:/lab/display_vga/coe/test7.coe
add_files e:/lab/coe/test7.coe
add_files -quiet E:/lab/display_vga/display_vga.runs/dcm_25m_synth_1/dcm_25m.dcp
set_property used_in_implementation false [get_files E:/lab/display_vga/display_vga.runs/dcm_25m_synth_1/dcm_25m.dcp]
add_files -quiet E:/lab/display_vga/display_vga.runs/logo_rom_synth_1/logo_rom.dcp
set_property used_in_implementation false [get_files E:/lab/display_vga/display_vga.runs/logo_rom_synth_1/logo_rom.dcp]
read_verilog -library xil_defaultlib {
  E:/lab/display_vga/display_vga.srcs/sources_1/imports/sources/debounce.v
  E:/lab/display_vga/display_vga.srcs/sources_1/imports/sources/vga_timing.v
  E:/lab/display_vga/display_vga.srcs/sources_1/imports/sources/top_flyinglogo.v
}
read_xdc E:/lab/display_vga/display_vga.srcs/constrs_1/new/display_vga.xdc
set_property used_in_implementation false [get_files E:/lab/display_vga/display_vga.srcs/constrs_1/new/display_vga.xdc]

synth_design -top top_flyinglogo -part xc7a35tcsg324-1
write_checkpoint -noxdef top_flyinglogo.dcp
catch { report_utilization -file top_flyinglogo_utilization_synth.rpt -pb top_flyinglogo_utilization_synth.pb }
