# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/lab/display_vga/display_vga.cache/wt [current_project]
set_property parent.project_path E:/lab/display_vga/display_vga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom.xci
set_property used_in_implementation false [get_files -all e:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom.dcp]
set_property is_locked true [get_files E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom.xci]

synth_design -top logo_rom -part xc7a35tcsg324-1 -mode out_of_context
rename_ref -prefix_all logo_rom_
write_checkpoint -noxdef logo_rom.dcp
catch { report_utilization -file logo_rom_utilization_synth.rpt -pb logo_rom_utilization_synth.pb }
if { [catch {
  file copy -force E:/lab/display_vga/display_vga.runs/logo_rom_synth_1/logo_rom.dcp E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir E:/lab/display_vga/display_vga.ip_user_files/ip/logo_rom]} {
  catch { 
    file copy -force E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom_stub.v E:/lab/display_vga/display_vga.ip_user_files/ip/logo_rom
  }
}

if {[file isdir E:/lab/display_vga/display_vga.ip_user_files/ip/logo_rom]} {
  catch { 
    file copy -force E:/lab/display_vga/display_vga.srcs/sources_1/ip/logo_rom/logo_rom_stub.vhdl E:/lab/display_vga/display_vga.ip_user_files/ip/logo_rom
  }
}
